version: '3.9'

services:
  auth:
    build:
      context: ./services/auth
    container_name: auth-service
    ports:
      - "8001:8080"
    networks:
      - telegram-net

  user:
    build:
      context: ./services/user
    container_name: user-service
    ports:
      - "8002:8080"
    networks:
      - telegram-net

  chat:
    build:
      context: ./services/chat
    container_name: chat-service
    ports:
      - "8003:8080"
    networks:
      - telegram-net

networks:
  telegram-net:
    driver: bridge
